<a href="https://colab.research.google.com/github/akshaypat444/tensorflow_practice/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Tensors

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.14.0


In [ ]:
## Creating tensors with tf.constants()
scalar = tf.constant(7)

vector = tf.constant([10, 10])

matrix = tf.constant([[10,7],
                      [7,10]])

matrix2 = tf.constant(([[5., 4.],
                       [8.,3.],
                       [6.,7.]]), dtype=tf.float16)

tensor = tf.constant([[[1,2,3,],
                       [2,3,4,]],
                      [[5,6,7,],
                        [6,7,8,]],
                      [[5,6,7],
                       [5,4,3]]
                     ])
print(tensor.ndim)

3


In [ ]:
## Creating tensors with tf.Variable()

In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# object does not support item assignment
# unchangeable_tensor[0] = 7

## Creating a random tensor

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

In [ ]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

## Shuffle a Tensor

In [ ]:
not_shuffled = tf.Variable([[10,7],
                            [2,3],
                            [8,9]])
not_shuffled

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [ 8,  9]], dtype=int32)>

In [ ]:
shuffled_tensor = tf.random.shuffle(not_shuffled)
shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  9],
       [10,  7],
       [ 2,  3]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
shuffled_tensor2 = tf.random.shuffle(not_shuffled, seed=42)
shuffled_tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [ 8,  9]], dtype=int32)>

## Other ways to make tensors

In [ ]:
tf.ones([5,6])

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=[5,6])

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
np_array = np.arange(1,25)
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
tf.constant(np_array)

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [ ]:
tf.constant(np_array, shape=(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

## Getting information from the tensors
1. Shape
2. Axis /Dimension
3. Rank
4. Size

In [ ]:
rank_4_tensor = tf.zeros([2,3,4,5])

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

## Attributes of tensors

In [ ]:
rank_4_tensor.dtype

tf.float32

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank_4_tensor.shape[0]

2

In [ ]:
rank_4_tensor.shape[-1]

5

In [ ]:
tf.size(rank_4_tensor).numpy()

120

# Indexing Tensors

In [ ]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10, 7], [5,6]])

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6]], dtype=int32)>

In [ ]:
rank_2_tensor.ndim

2

In [ ]:
rank_2_tensor.shape

TensorShape([2, 2])

In [ ]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6], dtype=int32)>

In [ ]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 5],
        [ 6]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 5],
        [ 6]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis = 1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 5,  6]]], dtype=int32)>

## Manipulating tensors (tensor operations)

In [ ]:
tensor = tf.constant([[6 ,7], [8, 9]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 7],
       [8, 9]], dtype=int32)>

In [ ]:
tensor + 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
tensor - 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
tensor * 10
# tf.math.multiply(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[60, 70],
       [80, 90]], dtype=int32)>

In [ ]:
tensor / 3

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2.        , 2.33333333],
       [2.66666667, 3.        ]])>

## Matrix Multiplication

In [ ]:
print(tensor)

tf.Tensor(
[[6 7]
 [8 9]], shape=(2, 2), dtype=int32)


In [ ]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 92, 105],
       [120, 137]], dtype=int32)>

In [ ]:
# Element wise multiplication
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[36, 49],
       [64, 81]], dtype=int32)>

In [ ]:
A = tf.constant([[1,2,5],
                 [7,2,1],
                 [3,3,3]])
B = tf.constant([[3,5],
                 [6,7],
                 [1,8]])

In [ ]:
C = tf.matmul(A,B)
C

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# '@' operator does matrix multiplication in python
A @ B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
A.shape, B.shape, C.shape

(TensorShape([3, 3]), TensorShape([3, 2]), TensorShape([3, 2]))

In [ ]:
A.ndim, B.ndim, C.ndim

(2, 2, 2)

In [ ]:
# Matrix Multiplication is also known as dot product


In [ ]:
tf.reshape(C, shape=(6,1))

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[20],
       [59],
       [34],
       [57],
       [30],
       [60]], dtype=int32)>

In [ ]:
# Transpose
tf.transpose(C)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[20, 34, 30],
       [59, 57, 60]], dtype=int32)>

In [ ]:
# Matrix multiplication with transpose and with reshape can be different

## The dot product - Is another name for matrix multiplication
**Matrix multiplication can be done in 2 ways**
1. tf.matmul()
2. tf.tensordot()

In [ ]:
A

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [ ]:
B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [ ]:
tf.tensordot(tf.transpose(A), B, axes=0)

<tf.Tensor: shape=(3, 3, 3, 2), dtype=int32, numpy=
array([[[[ 3,  5],
         [ 6,  7],
         [ 1,  8]],

        [[21, 35],
         [42, 49],
         [ 7, 56]],

        [[ 9, 15],
         [18, 21],
         [ 3, 24]]],


       [[[ 6, 10],
         [12, 14],
         [ 2, 16]],

        [[ 6, 10],
         [12, 14],
         [ 2, 16]],

        [[ 9, 15],
         [18, 21],
         [ 3, 24]]],


       [[[15, 25],
         [30, 35],
         [ 5, 40]],

        [[ 3,  5],
         [ 6,  7],
         [ 1,  8]],

        [[ 9, 15],
         [18, 21],
         [ 3, 24]]]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(A), B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[48, 78],
       [21, 48],
       [24, 56]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(A, shape=(3, 3)), B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

# Changing the datatype of the tensor
**tf.cast()**

In [ ]:
B = tf.constant([7.2, 3.4])
B.dtype

tf.float32

In [ ]:
F = tf.constant([3, 6])
F.dtype

tf.int32

In [ ]:
# Changing the datatype using tf.cast()
B = tf.cast(B, dtype = tf.float16)

In [ ]:
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([7.2, 3.4], dtype=float16)>

# Aggregating the tensors

In [ ]:
# Get the absolute values
tensor_a = tf.constant([-7, -10])
print(tensor_a)
tf.abs(tensor_a)

tf.Tensor([ -7 -10], shape=(2,), dtype=int32)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# Create a random tensor
import numpy as np
tensor_b = tf.constant(np.random.randint(0, 100, size=50))
tensor_b

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([30, 79,  3, 55, 11, 78, 97, 47,  3, 33, 83,  2, 82, 82, 35, 58, 91,
       82, 53, 14, 57, 39, 18, 13, 99, 39, 85, 77, 73, 94, 39, 85, 31, 44,
       61, 31, 49, 37, 92, 44, 74, 84, 94, 65,  6, 97, 28, 88, 98, 81])>

In [ ]:
# Find the mininum
tf.reduce_min(tensor_b)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
# Find the maximum
tf.reduce_max(tensor_b)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# Find the mean
tf.reduce_mean(tensor_b)

<tf.Tensor: shape=(), dtype=int64, numpy=56>

In [ ]:
# Find the sum
tf.reduce_sum(tensor_b)

<tf.Tensor: shape=(), dtype=int64, numpy=2840>

In [ ]:
# Find the variance
tf.math.reduce_variance(tf.cast(tensor_b, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=897.08>

In [ ]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(tensor_b, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.951294>

## Using tensorflow_probability module

In [ ]:
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(tensor_b)

<tf.Tensor: shape=(), dtype=int64, numpy=897>

In [ ]:
tfp.stats.stddev(tf.cast(tensor_b, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=29.95>

## Finding positional maximum and minimum

In [ ]:
tf.math.argmax(tensor_b)

<tf.Tensor: shape=(), dtype=int64, numpy=24>

In [ ]:
tf.math.argmin(tensor_b)

<tf.Tensor: shape=(), dtype=int64, numpy=11>

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
assert tf.reduce_max(F) == F[tf.argmax(F)] == tf.reduce_max(F)

## Squeezing the tensor

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))

In [ ]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

## One hot encoding tensors

In [ ]:
my_list = [1,2,3,4]
tf.one_hot(my_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(my_list, depth=4, on_value="#", off_value="*")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'*', b'#', b'*', b'*'],
       [b'*', b'*', b'#', b'*'],
       [b'*', b'*', b'*', b'#'],
       [b'*', b'*', b'*', b'*']], dtype=object)>

## Mathematical operations

In [ ]:
tensor_h = tf.range(1, 10)
tensor_h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(tensor_h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(tensor_h, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(tensor_h, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and Numpy

In [ ]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert tensor to numpy array
np.array(J)

array([ 3.,  7., 10.])

In [ ]:
# Convert array to tensor
J.numpy()

array([ 3.,  7., 10.])

## Finding access to GPUs

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]